import time

print("Let's play a game!")
print()

animalName1 = input("What is the first animal's name? ")
animalType = input(f"What type of animal is {animalName1}? ")
noun1 = input("Now we need a noun! ")
size1 = input("We need a size: ")
color1 = input("And a color: ")
animal2 = input("Let's do an type of animal: ")
adjective1 = input("How's about an adjective: ")
clothing1 = input("And an article of clothing? ")
number1 = input("Pick a number from 1 - 120,324,321,576,342,793,325: ")
food1 = input("What's your favorite food? ")
size2 = input("I think we should do another size: ")
smell1 = input("What's something you LOVE smelling? ")
food2 = input("What's your least favorite food? ")
somethingGross1 = input("And something totally nasty, like the worst thing ever: ")
number2 = input("This number needs to be between 54 and 1,049,204: ")
bodyPart1 = input("An age appropriate body part: ")
object1 = input("Name an object that spins: ")
adjective2 = input("Give me an adjective: ")
age1 = input("How about an age (like young, old, teenage, ancient): ")
animal3 = input("Another animal type: ")
animalName2 = input("Give that animal a silly name: ")
food3 = input("Name a drink or food: ")
musicType1 = input("What kind of music (like rock, country, disco): ")
size3 = input("A size (tiny, huge, medium, gigantic): ")
color2 = input("Another color: ")
shape1 = input("A shape (like circle, square, triangle): ")
band1 = input("Name a band or musician: ")
verb1 = input("An action word ending in -ing (like dancing, jumping, singing): ")
food4 = input("One more food: ")
object2 = input("A big object: ")

#story
print(f"{animalName1} was the bravest space {animalType} in the entire galaxy. One day, {animalName1} was flying through space in a giant rocket-powered {noun1} when suddenly, disaster struck!")
time.sleep(2)
print(f"A {size1} {color1} {animal2} floated past the window, wearing nothing but {adjective1} {clothing1} and eating {number1} {food1}. The {animal2} let out an {size2} FAAAAAARRRT that smelled like {smell1} {food2} mixed with {somethingGross1}!")
time.sleep(2)
print(f"The fart was so powerful it pushed the {noun1} backward at {number2} miles per hour! {animalName1} screamed \"OH NO! MY BEAUTIFUL {bodyPart1}!\" as the {noun1} started spinning like a {object1}.")
time.sleep(2)
print(f"Just then, a {adjective2} {age1} {animal3} named {animalName2} appeared on the video screen. \"Quick!\" shouted {animalName2}. \"You must counteract the fart with a {food3} and some {musicType1} music!\"")
time.sleep(2)
print(f"{animalName1} grabbed the nearest {food3} and pressed the {size3} {color2} {shape1} labeled \"EMERGENCY {musicType1}.\" Suddenly, {band1} started playing and everyone started {verb1}, including the farting {animal2}!")
time.sleep(2)
print(f"The {musicType1} power was so strong that the {noun1} stopped spinning and {animalName1} was saved! The {animal2} apologized by giving {animalName1} a {food4} the size of a {object2}.")
time.sleep(2)
print(f"And that's how {animalName1} became the hero of the Milky Way galaxy and also why we never eat {food1} in space anymore.")
time.sleep(2)
print("THE END!!!!")